<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyName>Dudu.AssetTool</AssemblyName>
    <RootNamespace>Dudu.AssetTool</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Dudu.Core/Dudu.Core.csproj" />
    <PackageReference Include="SkiaSharp" />
  </ItemGroup>

</Project>
